name: masayel_app
description: "ইসলামিক মাসায়েল অ্যাপ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1         # SQLite ডাটাবেসের জন্য
  path: ^1.9.0             # ফাইল পাথ ম্যানেজ করার জন্য
  share_plus: ^10.0.0      # মাসআলা শেয়ার করার জন্য
  shared_preferences: ^2.5.5
  http: ^1.2.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.10.7
  url_launcher: ^6.3.0     # কাস্টম নোটিশের লিংক খোলার জন্য
  timezone: ^0.10.0        # 🟢 ভার্সন আপডেট করা হয়েছে (^0.10.0)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/developer.jpg
    - assets/database/masayel.db

  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
    - family: TraditionalArabic
      fonts:
        - asset: assets/fonts/TraditionalArabicRegular.ttf
    - family: JameelNoori
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf