name: masayel_app
description: "ইসলামিক মাসায়েল অ্যাপ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.2
  window_manager: ^0.3.9
  path: ^1.9.0
  share_plus: ^10.0.0
  shared_preferences: ^2.5.5
  http: ^1.2.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.10.7
  url_launcher: ^6.3.0
  timezone: ^0.10.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/developer.jpg
    - assets/database/masayel.db

  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
    - family: TraditionalArabic
      fonts:
        - asset: assets/fonts/TraditionalArabicRegular.ttf
    - family: JameelNoori
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf