name: Build Windows Exe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Enable Windows Platform in Project
        run: flutter create --platforms=windows .

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Executable (.exe)
        run: flutter build windows --release

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MasayelApp-Windows-Software
          path: build/windows/x64/runner/Release/