name: Build Windows Exe & Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Dependencies
        run: flutter pub get

      # 🟢 ১. উইন্ডোজ এক্সই (.exe) বিল্ড করা (MSVC Coroutine Warning Bypass সহ)
      - name: Build Windows
        env:
          CL: "/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"
        run: flutter build windows --release

      # 🟢 ২. অ্যান্ড্রয়েড এপিকে (.apk) বিল্ড করা
      - name: Build Android APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      # 🚀 উইন্ডোজ অ্যাপ জিপ বানিয়ে আপলোড
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: Masayel-Windows-App
          path: build/windows/x64/runner/Release/

      # 🚀 অ্যান্ড্রয়েড APK ফাইল আপলোড
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Masayel-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk